### ISSUE TITLE
Cannot bind mouse huttons in ablity hotkeys

### ISSUE THREAD

**Issue by AutomaticFrenzy** [campbt/DanceDanceRotation#1]
I use mouse buttons for my elite and my healing and am not able to bind them

**Comment by campbt** [comment]
Unfortunately, that is currently a limitation of BlishHUD, but it is being worked on. Once Blish adds support for them, they should begin working in DanceDanceRotation.

You could set up something like Autohotkey or a macro to have the mouse button fire a different actually bindable key, but, I also have mouse key bindings, and I just practice the rotation normally and take the Miss.
