### ISSUE TITLE
[Bug] Show Next Abilities + Practice Speeds

### ISSUE THREAD

**Issue by FrenchGucho** [campbt/DanceDanceRotation#7]
If you have "Show Next Abilities" enabled while your Note Speed and Note Pace is at a lower value than 100%, the "Show Next Abilities" notes also take a noticeable delay to update (even though it shows the "Perfect"/"Great" for that skill being pressed). Can be recreated pretty easily if you set both Note Speed and Note Pace to a low number like 30%.

Ex. https://imgur.com/a/hOUHWSz

It takes 16 seconds for the first note in the preview to respond for the song Condition Druid [SC] with the settings 30%/30%/0:00.

**Comment by campbt** [comment]
Thanks for the report. I've fixed this in 1.3.1, which should be released soon.
