### ISSUE TITLE
new icons not available

### ISSUE THREAD

**Issue by kontenlo** [campbt/DanceDanceRotation#8]
new icons of skills recently added i.e: axe skills on thief.

**Comment by campbt** [comment]
I think that's mostly from bad IDs from the Composer tool. But, I've added support for SotO weapons in 1.4.0 along with a new composer tool version that should recognize the new weapon skills (and ignore some additional things like relics)

**Comment by campbt** [comment]
1.4.0 is released, so marking this fixed
