### ISSUE TITLE
"Ability Bar Style" doesn't "recognize utility/elite skill keystrokes (including "start with first skill")

### ISSUE THREAD

**Issue by b4ttl3m4st3r** [campbt/DanceDanceRotation#9]
### Version
- Blish HUD 1.0.0
- DanceDanceRotation 1.5.1

### Description

Hi there and thank you for this cool plugin!
I was recommended this plugin the day before and pretty much enjoy it; planning to use it more frequently in the future.

However, I figured out that the "Ability Bar Style" doesn't seem to recognize me pressing any utility or elite skill. They always miss, no matter in what time I press them and no matter which "utility skill remapping" I am using. The issue is best revealed, when you enable the "Start with first Skill"-feature and the rotation begins with an utility skill or the elite skill. The keystroke recognition and the auto-start of/with an utility/elite skill works flawlessly when using another notes orientation other than "Ability Bar Style".

### To Reproduce
1. Install the module
2. Restart BlishHUD
3. Enable the module
4. Within the module settings
    - select "Ability Bar Style" as notes orientation
    - enable "Start with first skill"
    - set your ability hotkeys to match with your in-game hotkeys
5. Open the Dance Dance Rotation Window (NotesContainer)
6. Within the "Song List"
    - Select an appropriate rotation that starts with an utility/elite skill. Example:
        a. Power Weaver [SC] (Starting with utility skill "Lightning Storm")
        b. Condition Daredevil [SC] (Starting with elite skill "Thieves Guild")
        c. Condition Quickness Untamed [SC] (Starting with utility skill "Viper's Nest")
8. Within the "Song Info"
    - Rotate the utility skill positions until it matches your in-game skill positions
9. Try to start the rotation by pressing the utility/elite skill

### Attempts to solve the problem
- restarting/reinstalling BlishHUD
- restarting/reinstalling the plugin itself (also removed config folder)
- tried various plugin config combinations to narrow down the problem
- tried different classes and "songs".
- tried different (wrong) remaps of utility skills (none worked)
- tried with different interface sizes (normal, small, larger)

### Screenshot
![image](https://github.com/campbt/DanceDanceRotation/assets/1309905/82702994-4a27-47a2-b5f9-89f4be3267f1)
If you look at the picture, you will notice that the symbol for the skill is a bitt off to the right from the view of the gray hole-bar. (Compared to how the code seem to recognize a correct keystroke, it might be related to the issue. I'm playing in windowed fullscreen with interface size "normal".)

### Code
As a programmer who is not familiar with C# and Blish plugins, I can (and have) read the code and it's  syntax, but I don't fully understand the entire context. So I can only give you some lines of code as a vague idea of where the problem might lie without any idea of how exactly they work together:

https://github.com/campbt/DanceDanceRotation/blob/8aa214e9f3a0ba64f2de9ce2a6537a9ca7c7d47c/DanceDanceRotationModule/Views/NotesContainer.cs#L604-L606
https://github.com/campbt/DanceDanceRotation/blob/8aa214e9f3a0ba64f2de9ce2a6537a9ca7c7d47c/DanceDanceRotationModule/Views/NotesContainer.cs#L699-L703

I just hope this helps and you can have a quick look into it to find the issue in no time.
It would be nice if this problem could be solved one day. :)
Thank you!

**Comment by campbt** [comment]
Thanks for such a thorough bug report. I can't take a look at this for a few days, but I'll try to get it fixed as soon as possible.

**Comment by campbt** [comment]
I believe I have found the fix and pushed it up as 1.5.2

It should be available in BlishHUD's package manager in the next day or so.

Thanks again for the great report. Pretty spot on for the code, even.

**Comment by b4ttl3m4st3r** [comment]
Tested and is fixed for me in v1.5.2.
Thanks for the quick submit!
